# Generated by Django 6.0.3 on 2026-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=100)),
                ('Emp_ID', models.EmailField(max_length=254)),
                ('Designation', models.CharField(max_length=100)),
                ('Date_of_joining', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Annual_CTC', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
            ],
        ),
    ]
