# Generated by Django 6.0.3 on 2026-04-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='EmpName',
            new_name='Emp_Name',
        ),
    ]
