# Generated by Django 6.0.3 on 2026-04-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_empname_employee_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latestnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
