# Generated by Django 6.0.3 on 2026-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_latestnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestnews',
            old_name='description',
            new_name='details',
        ),
    ]
