# Generated by Django 6.0.3 on 2026-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_rename_description_latestnews_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='title',
            field=models.CharField(default='No Title', max_length=100),
            preserve_default=False,
        ),
    ]
