# Generated by Django 6.0.3 on 2026-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_calendar_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('skills', models.TextField()),
                ('current_ctc', models.CharField(max_length=50)),
                ('notice_period', models.CharField(max_length=50)),
            ],
        ),
    ]
